version: '3'
services:
  database-migration:
    image: openjdk:17.0.2-slim
    command: ./gradlew flywayMigrate -i
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
