version: '3'
services:
  database-migration:
    image: openjdk:17.0.2-slim
    command: ./gradlew flywayMigrate -i
    environment:
      DB_HOSTNAME: ${GITHUB_USERNAME}
      DB_NAME: ${GITHUB_TOKEN}
      DB_USERNAME: ${GITHUB_TOKEN}
      DB_PASSWORD: ${GITHUB_TOKEN}
